title = "Tears Of Silence"
theme = "solar-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright=" "

[params]
  scheme = "gray" # light, dark, gray or preference
  description = "info@tearsofsilence.com"
